### ISSUE TITLE
Clarify utilities & globals name

### ISSUE THREAD

**Issue by puzrin** [littlevgl/lv_i18n#1]
Utilities and functions/variables should not conflict with other programs/libs

**Comment by kisvegabor** [comment]
I can speak about the names and types on `C` side. 
IMO a `lang` prefix would be enough. So:
- `lang_en_gb` + `lang_en_gb_plural_rule`

**Comment by puzrin** [comment]
Closing:

- utility name seems ok
- variables can be discussed in C spec and template review.
