### ISSUE TITLE
Release/Announce of lv_i18n?

### ISSUE THREAD

**Issue by puzrin** [littlevgl/lv_i18n#11]
Is there any process of announce "new feature" to interested parties?

I'd like people try to use this package and report first impression.

**Comment by kisvegabor** [comment]
Hopefully, in a week I will add the biggest API breaking updates to `dev-6.0`. I suggest opening an issue after it and ask people to test the new features.

**Comment by puzrin** [comment]
Ok. I did not tagged release and did not published in npm, but readme contains info how to install directly from github.

Will continue as soon as someone says "i tried and it's not horrible".

**Comment by kisvegabor** [comment]
Fine :)

**Comment by puzrin** [comment]
Did anyone succeeded?

I closed pending tails and added info how to run via [npx](https://github.com/littlevgl/lv_i18n#installrun-the-script) (without install).

If anyone used this tool, i could make official release.

**Comment by kisvegabor** [comment]
There is no feedback yet. I'll try the latest release again in one of my projects today. 
I encourage everybody if he has something great to tell, to write a blog post about it. Posts are:
- searchable
- shareable
- linkable

so it would be a good place the describe this tool and share it. The README is quite complete now but a post:
- can introduce the problem in more details (every user could know/understand why it is important)
- can compare lv_i18n to other tools
- and show a simple but complete example

As lv_i18n is independent of LittlevGL you can use it with the current version too.

Would you be interested in it?

---
@BrianPugh Jolt Wallet has multi langage support. Have you alredy tried or do you planning to try this tool?

**Comment by puzrin** [comment]
> Would you be interested in it?

I'd prefer to participate in something different :)

**Comment by kisvegabor** [comment]
> I'd prefer to participate in something different :)

No problem. 

I installed lv_i18n with `npm i littlevgl/lv_i18n -g` again but got the following error on compile:

```
lv_i18n compile -t './*.yml' -o './'
Base locale 'en-GB' (autodetected)
cp: no such file or directory: /home/kisvegabor/.nvm/versions/node/v11.2.0/lib/node_modules/lv_i18n/src/lv_i18n.h
/home/kisvegabor/.nvm/versions/node/v11.2.0/lib/node_modules/lv_i18n/lv_i18n.js:17
  throw err;
  ^

Error: ENOENT: no such file or directory, open '/home/kisvegabor/.nvm/versions/node/v11.2.0/lib/node_modules/lv_i18n/src/lv_i18n.template.c'

```

**Comment by puzrin** [comment]
https://github.com/littlevgl/lv_i18n/commit/dfe5d67b03a2b8be1bb67945d9e53586314c36e2

Try again please.

```sh
npm uninstall lv_i18n -g
npm i littlevgl/lv_i18n -g
```

**Comment by kisvegabor** [comment]
Compiled successfully, thank you!

**Comment by kisvegabor** [comment]
With this I tested:
- Install
- Markup in C
- Create template yml files
- extract
- compile

So the basic features seem to work!

**Comment by seyyah** [comment]
Great job :clap: 

My test code is here

```yaml
# translations/tr-TR.yml
tr-TR:
  title1: Başlık1

# translations/en-EN.yml
en:
  title1: Title1
```

```c
#include "lv_i18n/lv_i18n.h"

char label[100];

/* Load translations & default locale (usually, done once) */
lv_i18n_init(lv_i18n_language_pack);

/* Set active locale (can be switched anytime) */
lv_i18n_set_locale("tr-TR");
strcpy(label, _("title1"));
printf("TR: label: %s \n", label);

lv_i18n_set_locale("en-US");
strcpy(label, _("title1"));
printf("EN: label: %s \n", label);
```

Result is

```sh
TR: label: Başlık1
EN: label: Title1
```

I suggest to rename `lv_i18n_language_pack` variable name to `lv_i18n_lang_pack` in the generated `lv_i18n.c`.

**Comment by seyyah** [comment]
I meet a simple bug. ` // uint32_t n = op_n(n); UNUSED(n);` is buggy.

```c
static uint8_t tr_tr_plural_fn(int32_t num)
{
    uint32_t n = op_n(num); UNUSED(n);
    // uint32_t n = op_n(n); UNUSED(n);

    if ((n == 1)) return LV_I18N_PLURAL_TYPE_ONE;
    return LV_I18N_PLURAL_TYPE_OTHER;
}
```

**Comment by puzrin** [comment]
> I suggest to rename `lv_i18n_language_pack` variable name to `lv_i18n_lang_pack` in the generated `lv_i18n.c`.

I see no need, but if you think this should be voted - create a separate issue. Also, consider use separate issues for reports. This one is mostly about release process.

> I meet a simple bug. `// uint32_t n = op_n(n); UNUSED(n);` is buggy.

Fixed in https://github.com/littlevgl/lv_i18n/commit/96678f7446d8c8f5106a8ad8b36da96c1664f604, thank you for details.

**Comment by BrianPugh** [comment]
@kisvegabor sorry just saw this. I'm still currently using my old language system, but I do intend moving over whenever i finish some other stuff higher on the priority list. One of the things higher on my list is migrating to dev-6.0 ;)

**Comment by kisvegabor** [comment]
@BrianPugh Great! Waiting for the feedback. :)

**Comment by puzrin** [comment]
Any news? I should add git tag and make npm publish. Need feedback at least "it doesn't look totally broken" :)

**Comment by kisvegabor** [comment]
It doesn't look totally broken! :) 

I'm using it in one of my projects. It works well but not all features were tested.

**Comment by puzrin** [comment]
Tagged and released 0.1.0.

@kisvegabor, @embeddedt, please register at https://www.npmjs.com/ and give me links to your accounts. I should give you ownership/publish permission for this package.

**Comment by kisvegabor** [comment]
> Tagged and released 0.1.0.

Awesome! :clap: :clap: :clap: 

Here is my profile: https://www.npmjs.com/~kisvegabor

**Comment by puzrin** [comment]
Added permissions.

**Comment by embeddedt** [comment]
https://www.npmjs.com/~embeddedt

**Comment by puzrin** [comment]
added
