### ISSUE TITLE
Extract: No phrases to translate

### ISSUE THREAD

**Issue by kisvegabor** [littlevgl/lv_i18n#13]
I attached a super simple code which I use to test. [i18n_test.zip](https://github.com/littlevgl/lv_i18n/files/2930178/i18n_test.zip)

On `lv_i18n extract -s './**.+(c|cpp|h|hpp)' -t './*.yml'`  
I get `No phrases to translate`

**Comment by puzrin** [comment]
Try temporary:

`printf(_("msgid1"));` => `printf( _("msgid1") );`

https://github.com/littlevgl/lv_i18n/blob/d63564f35c7c8ffee6c1552c553ff526492b47ca/lib/parser.js#L16-L28

Current regexes are very primitive, need to improve. It would be nice to copy-paste from original gettext.

**Comment by kisvegabor** [comment]
With added spaces, it's working. I think there is only a few character which can be before `_`: 
- ` `
- `(`
- `)`
- `,`
- `;` (mabe)

What is the problem with filtering to these characters

**Comment by kisvegabor** [comment]
Works, thank you!
