### ISSUE TITLE
Subfodlers are not checked

### ISSUE THREAD

**Issue by kisvegabor** [littlevgl/lv_i18n#14]
With ` lv_i18n extract -s './**.+(c|cpp|h|hpp)' -t './*.yml'`  the `_("msgid")` patterns are not found in the subfolders. I got `No phrases to translate`. With `-s '.path/to/folder/*.+(c|cpp|h|hpp)'` it's working.

**Comment by puzrin** [comment]
That's strange, probably wrong glob pattern.

Could you attach zip with sample and commands to run?

**Comment by kisvegabor** [comment]
Sure!

[i18n_test.zip](https://github.com/littlevgl/lv_i18n/files/2930697/i18n_test.zip)

`lv_i18n extract -s './**.+(c|cpp|h|hpp)' -t './*.yml'` finds the phrases only in `source.c` and not in `source_dir.c` and `source_dir2.c`

**Comment by puzrin** [comment]
https://github.com/isaacs/node-glob#readme

Change search path to this: `lv_i18n extract -s './**/*.+(c|cpp|h|hpp)' -t './*.yml'`

- `**` match zero or more subdirs
- `*` match inside name

**Comment by kisvegabor** [comment]
Working, thanks!
