### ISSUE TITLE
Autodetect default compiler locale 

### ISSUE THREAD

**Issue by puzrin** [littlevgl/lv_i18n#18]
**Problem**

1. Default locale is english, but exact name depends on user preferences
   - `en-GB`
   - `en`
   - `en-US`
2. Manual locale selection (if not `en-GB`) is not nice.

It would be nice to solve this somehow.

**Solution**

`en-GB`, `en` & `en-US` are rarely used simultaniously in real world. We can search available, and if only one exists - select it as default.

**Comment by kisvegabor** [comment]
What about choosing the first `en*`?

**Comment by puzrin** [comment]
> What about choosing the first `en*`?

~ the same result, but idea of strings sort is interesting.
