### ISSUE TITLE
C public API

### ISSUE THREAD

**Issue by puzrin** [littlevgl/lv_i18n#2]
User API
--------

Based on `gettext` principles, but focused on simplicity.

Usage example:

```C
#include "lv_i18n.h"       // library
#include "translations.h"  // generated translations

lv_i18n_init(i18n_translations);    // load translations & default locale
lv_i18n_set_locale('ru-RU');        // set active locale

// In other file:

#define _(t)     lv_i18n_get_text(t)
#define _p(t, p) lv_i18n_get_text_plural(t, p)

char* mytext = _("my text to translate");
char* my_plural_text = _p("my text to translate", number);
```

### bool lv_i18n_init(lv_i18n_translations_struct translations)

Attach generated translations to be used by `lv_i18n_get_text()`.

### bool lv_i18n_set_locale(char* locale_name)

Set locale to be used by `lv_i18n_get_text()`.

- _name_ - locale name, case insensitive (`en-GB`, `ru-RU`). If empty string passed - switch to default locale.
  - Should be case insensitive and allow `_` instead of `-`.
  - Locale names are not restricted to standard list, but only ascii chars allowed (for simple normalization).

Returns `false` if locale not found (use default one then).

### char* lv_i18n_get_text(char *text)

Mapped to `_(...)` or `_t(...)` via `#define`

Get translated text. If not translated, return fallback (try default locale first, then function param if default not exists)

### char* lv_i18n_get_text_plural(char *text, int32_t plural)

Mapped to `_p(...)` or `_tp(...)` via `#define`

Get plural form of translated text. Use current local to select proper plural algorythm. If not translated, fallback to default locale first, then to input param.

(!) don't forget to switch plural selector when fallback used 

## Pending

- Clarify function names, to not conflict with other libs.
  - Probably, `lv_t()`, `lv_t_init()`, `lv_t_locale()`

**Comment by puzrin** [comment]
More to discuss:

- ? Seems get_locale() missed, may be useful to restore temporary switched locale. Not sure.
- `gettext()` now relies on clobal state (selected locale). Do we need altenatives to define locale implicit?

May be after discuss this will be moved to "postponed".

**Comment by kisvegabor** [comment]
I C you need to use all the arguments. So it's not working:
```c
i18n_set_locale('en-GB', true);  // set default (fallback) locale
i18n_set_locale('ru-RU');        // set active locale
```

I pushed a C example about my view here: https://github.com/littlevgl/i18n/tree/master/examples/manual
(Just illustration, not tested)

This way we can have a nice cute between the generated translations and program which will use it. I added some example lvgl functions to illustrate the usage. With the demonstrated method we don't need to declare any custom types in the translations.

The user only needs to organize the translations and plural rules into an array and pass them to his program as he needs them.

**Comment by puzrin** [comment]
> In C you need to use all the arguments. So it's not working:

Hm... everything in API was based on expectation, that it's possible to create multiple functions with the same name but different params list:

1. set_locate(string, bool)
2. set_locale(string)

The same for `_()`

Am i wrong? C does not allow such things?

**Comment by kisvegabor** [comment]
It needs to be 2 different functions with two different names.

**Comment by puzrin** [comment]
Ups... that's too bad. Need to reconsider all API then.

Did i mixed up this feature with CPP class methods? I remember, this is possible somewhere, if params combinations are unique (function can be determined by params types & order)

**Comment by puzrin** [comment]
https://stackoverflow.com/questions/7614672/can-a-c-function-have-multiple-signatures

May be worth to activate overloading automatically for CPP?

**Comment by puzrin** [comment]
https://stackoverflow.com/questions/479207/how-to-achieve-function-overloading-in-c/25026358#25026358

C11 has `_Generic` for such things. What are minimal lvgl requirements for compiler? Or you don't like overloading at all?

**Comment by kisvegabor** [comment]
Overloading might work in newer standards but people don't expect it from a C program. It would be distributing.

Anyway, it's not a big deal to have `_` and `_p`. These are two different functions in the gettext "family" too.

**Comment by puzrin** [comment]
> Anyway, it's not a big deal to have `_` and `_p`. These are two different functions in the gettext "family" too.

Ok. I only tried to keep api as simple as possible. Will review names and update names without overloads. We can add this back later via #define, if someone wish.

Can i ask you to avoid use `master` and `dev` branches if you are not 100% sure your commit is final? Any temporary branch name will be fine. I moved everything to https://github.com/littlevgl/i18n/tree/examples.

Regarding to your sample:

```c
    lv_lang_set_msgids(lang_msgids);
    lv_lang_set_translations(langs);
    lv_lang_set_plural_rules(plural_rules);
```

Can you explain why it would be good to have this methods separate? IMHO this looks like exposing internals without needs. Every user wish to have only one method "do_everything_awesome" :)

The same about separate `.c` file for each lang. Those are autogenerated, IMO one big file is preferable in this case.

```c
   lv_lang_set_default(LANG_ENGLISH);
```

Use enum here may make program not working without translation file, because enum will be undefined. I used strings like `ru-RU` for "weak linking". Any problems with this?

**Comment by kisvegabor** [comment]
> Can i ask you to avoid use `master` and `dev` branches if you are not 100% sure your commit is final? Any temporary branch name will be fine.

Ok, I'll do this way.


> The same about separate `.c` file for each lang. Those are autogenerated, IMO one big file is preferable in this case.

Good point. In this case, the arrays can be built (generated) by the script. I updated the [example](https://github.com/littlevgl/i18n/tree/examples/examples/manual).

> Use enum here may make program not working without translation file, because enum will be undefined.

Is it a problem if it's not working without translations? I don't think so.   
The translations are a very important part of your GUI so it's not a goal to work and without a "core" module like this.

> I used strings like `ru-RU` for "weak linking". Any problems with this?

`"ru-RU"` needs to be linked to a string array. It'd require a `struct` array where "language name" and "translation string" are used. However, the translation strings' array can be indexed simply with numbers too. 

You mentioned that you want to keep these scripts (and the generated code) as independent from lvgl as possible. I think it's a good idea as these will be general purpose tools. To achieve this we should limit the use of complex data structures (`struct`) and unique named types (`typedef`). In the example, only string arrays and numbers are used which makes this approach platform and language independent.

**Comment by puzrin** [comment]
> Is it a problem if it's not working without translations? I don't think so.

IMHO it is. That's a signal of bad code isolation.

Nobody prohibits use enums inside generated file. But i see no reasons to expose this outside in api.

> You mentioned that you want to keep these scripts (and the generated code) as independent from lvgl as possible. I think it's a good idea as these will be general purpose tools.

After thinking more about this idea, i decided to not go ahead so far. Design is universal, but implementaion may be different. For example, in Rust in may be native.

> To achieve this we should limit the use of complex data structures (`struct`) and unique named types (`typedef`). In the example, only string arrays and numbers are used which makes this approach platform and language independent.

IMHO that's not related. All you need is good isolation on API level. Nobody cares what you do inside, if compiler can eat this.

You can see, all API methods use simple types - strings, numbers. The only exclusion is `init()`, but it does not accepts user-selected data. Only machine-generated. May be we could relax it to untyped `*p`, but i see no reasons.

Anyway, i hope to stay aside of C internals. When API is nice - it's not principle what is inside if it works well.

**Comment by puzrin** [comment]
Updated first post with new names & signatures (to avoid mandatory func overload requirement).

1. Names are still subject to discuss.
2. I don't know how to define better number type in `lv_i18n_get_plural_text()`, if overloads are not available.
   - It should support all kinds of integers AND floats (in some langs fractionals can have different form)
   - if user has to cast types manually - that looks horrible IMO

**Comment by embeddedt** [comment]
@puzrin I think making two separate functions might be cleanest. We shouldn't depend on floating-point.

**Comment by puzrin** [comment]
> We shouldn't depend on floating-point.

Could you explain what do you mean?

> I think making two separate functions might be cleanest.

I could understand `lv_i18n_get_plural_text_f(float plrl, char* txt)` for floats. That's really specific case. But what about signed byte/word/long?

**Comment by embeddedt** [comment]
@puzrin 

> We shouldn't depend on floating-point.

1. Hardware floating-point is not available on all devices.
2. Software floating-point is slow(er) and adds to the code size.

**Comment by puzrin** [comment]
Thanks for explanation. I had no plans to use float without need. Problem is with lack of overloading - how to make api look nice without it.

**Comment by kisvegabor** [comment]
`gettext`'s  [documentation](https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html) suggest don't care with floats:
> Negative and floating-point values usually represent physical entities for which singular and plural don’t clearly apply. In such cases, there is no need to use ngettext; a simple gettext call with a form suitable for all values will do. For example:
>
>printf (gettext ("Time elapsed: %.3f seconds"),
>        num_milliseconds * 0.001);
>Even if num_milliseconds happens to be a multiple of 1000, the output
>
>Time elapsed: 1.000 seconds
>is acceptable in English, and similarly for other languages


> After thinking more about this idea, i decided to not go ahead so far. Design is universal, but implementaion may be different. For example, in Rust in may be native.

If we don't need to be so universal adn independent then we can really do it better on C side. I'll update the examples.

**Comment by kisvegabor** [comment]
I updated the examples.

**Comment by puzrin** [comment]
Example become more and more close to first message :)

Where is very important unresolver question. How to make `_p()` work with any type of integer numbers (byte, word, long, long long, + signed) without warnings and without force user to recast types manually?

**Comment by kisvegabor** [comment]
In these cases, I usually use `int32_t` as a parameter. Smaller types (`uint8_t`, `int16_t`) are implicitly cast without warning.  We only lose the 2 billion ... 4 billion range which is not an issue in our case.

**Comment by puzrin** [comment]
Great! Updated first post.

What do you think about plurals signature (position of plural param)?

- _First:_ `char* lv_i18n_get_plural_text(int32_t plural, char *text)` - this will allow extensions with va_args (for inlined sprintf) + overload function and use `_()` everywhere.
- _Last:_ `char* lv_i18n_get_plural_text(char *text, int32_t plural)` - this is a bit more beautiful, but significantly reduce possibility to beautify API in long term

**Comment by kisvegabor** [comment]
**Function name**
For me `lv_i18n_get_text_plural` seems more logical because it can leverage the autocomplate  better. Typing ``lv_i18n_get_text` will show how you can `get text`.

**Param order**
I vote for the second one. This order is approach is followed everywhere in the library. The first parameter is  "what we are working on". E.g. `lv_obj_set_width(btn, 100)`

**Comment by puzrin** [comment]
Ok. I think we can move forward with it. Updated first post (function name + signature)

See the end of first post:

- question about `_n()` - this looks like "something probably useful" but i could not understand/imagine any use case.
- general question about functions naming (now `lv_i18n_<something>`). May be someone has better ideas. Not principle, because people will use `_()` and `_p()` only.

**Comment by kisvegabor** [comment]
> * question about `_n()` - this looks like "something probably useful" but i could not understand/imagine any use case.

I also couldn't imagine a good use case for it.

**Comment by puzrin** [comment]
Updated first post - dropped `_n()`.

Will close this after commit skeleton to dev branch (first post will go to readme). Ina names change can be none later, if anyone has better idea. Not critical (not blocking).

**Comment by puzrin** [comment]
Close - landed to docs.

**Comment by puzrin** [comment]
> - question about `_n()` - this looks like "something probably useful" but i could not understand/imagine any use case.

Found possible reason for this feature.

Imagine, we need to extract only useable glyphs to generate fonts. Some phrases are not translated (strings in "select language" menu, "icons"). But we still need to process those to generate full symbols list.

**Comment by kisvegabor** [comment]
I think symbols and custom text are a different story. i18n should generate fonts for the translations only. It should be the ser responsibility to provide the fonts for symbols.

**Comment by puzrin** [comment]
You are right. Seems i'm too influenced by web/css in this question :)
