### ISSUE TITLE
[Suggestion] Rename from lv_i18n_language_pack to lv_i18n_lang_pack

### ISSUE THREAD

**Issue by seyyah** [littlevgl/lv_i18n#20]
`lv_i18n_init` function argument type is `lv_i18n_lang_pack_t` but `lv_i18n_language_pack` variable name is used in the generated file (`i18n.c`). I suggest to use `lv_i18n_lang_pack` variable name for consistency/readability purpose.

```c
int lv_i18n_init(const lv_i18n_lang_pack_t * langs);
```

In this case simple example'll be

```c
#include "lv_i18n/lv_i18n.h"

/* Load translations & default locale (usually, done once) */
lv_i18n_init(lv_i18n_lang_pack);
```

**Comment by puzrin** [comment]
```c
lv_i18n_init(lv_i18n_language_pack);
```

IMHO this is more readable. It's used only once and no need to save 4 chars.

But it's not principal for me, and i'm ready to accept any result of majority voting.

**Comment by kisvegabor** [comment]
For consistency, we really should use the same naming. So either:
- `lv_i18n_lang_pack_t lv_i18n_lang_pack;`
- `lv_i18n_language_pack_t lv_i18n_language_pack;`
is fine for me.

**Comment by puzrin** [comment]
If questions is in consistency only, i'd prefer `lv_i18n_language_pack_t lv_i18n_language_pack`.

Can do it right not, if nobody objects.

**Comment by seyyah** [comment]
We can use @kisvegabor' two styles at L114,

```c
const lv_i18n_lang_pack_t lv_i18n_language_pack[] = {
  &en_gb_lang,
  ...
};
```

For minimal code change, we prefer to use `lv_i18n_lang_pack_t lv_i18n_lang_pack;`. Otherwise we change extra `en_gb_lang`'s type,

```c
static const lv_i18n_lang_t de_de_lang = {...}
```

https://github.com/littlevgl/lv_i18n/blob/master/src/lv_i18n.template.c#L114

**Comment by puzrin** [comment]
Refered parts are:

- internals
- autogenerated

Their change costs nothing. IMHO the only thing, that does matter, is public API. In our case, this code in userspace:

```c
#include "lv_i18n/lv_i18n.h"

lv_i18n_init(lv_i18n_language_pack);
// or lv_i18n_init(lv_i18n_lang_pack);
```

That's the only difference, visible from user's point of view. I think, public API should not be driven by implementation details if possible.

**Comment by seyyah** [comment]
@puzrin your idea is suitable for me. So we may use

```c
lv_i18n_init(lv_i18n_language_pack);
```
