### ISSUE TITLE
Multiple translation files issue

### ISSUE THREAD

**Issue by barbiani** [littlevgl/lv_i18n#25]
I tried to follow the readme example and separate the translation to multiple yml files and get an error, while it worked file with a single translations.yml with multiple language entries.

```
$ ./lv_i18n.js extract -s ../*.c -t ../translations/*.yml
usage: lv_i18n.js extract [-h] -s <path> -t <path> [-c] [--orphaned-fail]
lv_i18n.js extract: error: Unrecognized arguments: ../translations/pt-BR.yml ../translations/ru-RU.yml.
```

Did I miss something?

**Comment by puzrin** [comment]
I don't see quotes around paths, and it's not clear if yaml files exists or not. Please create a sample repo, where your problem can be reproduced, and add instruction (step-by -step description what to do). Current info is not enough.

**Comment by puzrin** [comment]
Close - no feedback with details.
