### ISSUE TITLE
Postponed

### ISSUE THREAD

**Issue by puzrin** [littlevgl/lv_i18n#3]
This is cemetery area for ideas :).

- `sprintf` support in translations
  - Probably, overkill.
  - Unwanded possible memory allocations. Without sprintf `_()` will return just a pointer to `const` in flash/ram
- `_()` would be nice for plurals to. Functions overload is available in CPP and can be emulated in C11 via `_Generic`. Was removed because lvgl wish to support C89.
- Web transtators export/import #6

**Comment by kisvegabor** [comment]
In [this example](https://github.com/littlevgl/i18n/blob/master/examples/manual/main.c#L37) the use of `sprintf` is moved to the user's code. So he can decide to:
-  use `sprintf`
- write lightweighted custom formatter
- do nothing if only "static" texts are used

**Comment by puzrin** [comment]
Added note about overloaded functions.

**Comment by puzrin** [comment]
Close - i guess nothing of described will be implemented. No need to keep this open. Here we just land any kind of [crazy] ideas to keep brain free :).
