### ISSUE TITLE
Web transtators export/import

### ISSUE THREAD

**Issue by puzrin** [littlevgl/lv_i18n#6]
Frictionless integration with web translators required

- Convenient way to share efforts
- Firmware developper may not know all required languages

Questions to solve

- [ ] List of primary supported services
- [ ] Can we automate import/export without manual script run?
     - Ideally - post PR
     - Or create issue with stat after data update

**Comment by kisvegabor** [comment]
Do you already have experience with the online translator tools?

**Comment by puzrin** [comment]
Minimal. Helped to translate something many time ago, and studied approaches.

**Comment by puzrin** [comment]
- https://www.transifex.com/nodebb/nodebb/
  - I remember transifix as one of most convenient. They had limitation of ~ 200-1000 phrases for free use, that was enoughth for many thing. [Current](https://www.transifex.com/pricing/) pricing policy is unacceptable for OSS. Need to revisit alternatives
- https://weblate.org
  - Seems alive and actively developped. You can have own copy, or ask their free hosting for OSS projects. I don't know why they have only [235](https://hosted.weblate.org/projects/) OSS projects on their hosting.
  - They support PRs on github https://docs.weblate.org/en/latest/faq.html#how-to-create-automatic-worflow - did not studied but sounds promissing. Interesting, how do they support custom formats

**Comment by puzrin** [comment]
Close - moved to postponed.
