### ISSUE TITLE
Generated C files format

### ISSUE THREAD

**Issue by puzrin** [littlevgl/lv_i18n#7]
This file will be generated by `lv-tcompile` utility, and expected to contain "everything needed" to use in [C API](https://github.com/littlevgl/i18n/issues/2)

**TBD**

Memos:

- Each locale should include pluralizer function
- may be worth to create enum for plural names (`zero`, `one`, `two`, `few`, `many`, `other`), instead of ordered array.
- For details about plurals & functions codegen see https://github.com/nodeca/plurals-cldr and references at bottom of readme.

**Comment by puzrin** [comment]
Personal notes:

- This issue is on lowest level of i18n archtecture. It worth to solve all other [spec] issues first, to minimize rewrites.

**Comment by kisvegabor** [comment]
See:  https://github.com/littlevgl/i18n/issues/2#issuecomment-462016743

**Comment by puzrin** [comment]
@kisvegabor see huge commit in my branch. I've implemented almost everything in JS part. Will finish in couple of days and merge all to dev. Everything has 100% coverage :)

I think, it would be nice to move forward with C. Can anyone create a "template" of working file? That will help me very much.

How i see this:

- Template should consist of 2 parts (all in one file):
  - Demo data (struct), bordered with `#ifdef`.
  - Implementation of API functions.
    - It may be dirty, slow, but it should be correct
- When JS generator injects real content into head, demo data will be dimmed automatically.
- Everything should work without generator and be testable without JS at all.

Other things:

- Consider having multiple structs for plurals - separate one for each form. That may eliminate need of multi-dimentional arrays with non-fixed cell sizes.

So, we will have only linear lists to search for key: `singular`, `plural_zero`, `plural_one`, `plural_few`, ... Plus mapping "text" -> number to avoid duplication of long strings in each list.

**Comment by kisvegabor** [comment]
> see huge commit in my branch. I've implemented almost everything in JS part. Will finish in couple of days and merge all to dev. Everything has 100% coverage :)

Awesome!

> I think, it would be nice to move forward with C. Can anyone create a "template" of working file? That will help me very much.

I can create a template C file soon but to add the `lv_i18n` engine I need some time.

> Consider having multiple structs for plurals - separate one for each form. That may eliminate need of multi-dimentional arrays with non-fixed cell sizes.


It'd make things clearer but I must note that it means some extra memory usage because a pointer to the "msgid" needs to be stored in each array. However, it's a reasonable "cost" for clarity.

**Comment by puzrin** [comment]
I will look for a wile, what can i do about settings menu sketch and pio demo.

**Comment by kisvegabor** [comment]
I needed to deal with multi-language support in one of my projects so I implemented the new i18n engine. It's in the `i18n` branch of lvgl. The API is here:  https://github.com/littlevgl/lvgl/blob/i18n/lv_core/lv_i18n.h

The examples are updated accordingly: https://github.com/littlevgl/lv_i18n/tree/examples/examples/manual

**Comment by puzrin** [comment]
Hm... probably i don't understand idea. Why is it in lvgl? It's coupled with lvgl features (logs) and become difficult to test separate. Also, writing logs instead of status return (init,  set_locale), reduces testability to zero.

My idea was to make full solution here, ready to use. I expected independent implementation here, to decide how to move forward. For example, generator could make "header-only-file" with both data & implementation. It this case, lvgl core will not need any changes.

**Comment by kisvegabor** [comment]
> Hm... probably i don't understand idea. Why is it in lvgl? It's coupled with lvgl features (logs) and become difficult to test separate

Then maybe I also misunderstood something. I supposed it will replace the current `lv_lang` with the more advanced `lv_i18n`. However, it's not tightly coupled with lvgl and it seems it can work separately too. Then it is a question to make `i18n` support as built-in feature or as an external tool. 

It'd be easier to get started with `i18n` if it existed internally in lvgl and later the user can get the scripts.
On the other hand, it really would be easier to have a fully testable tool here which works standalone.

Creating a `scripts` folder inside `lvgl` and move these scripts there would solve the issue but in this case, it'd be difficult to detach the scripts from lvgl. But making the scripts portable was a requirement.

> Also, writing logs instead of status return (init, set_locale), reduces testability to zero.

`init` and `set_local` really can have return codes. but logs are also useful to see what happens in `get_text` and `get_text_plural`.

**Comment by puzrin** [comment]
Well, i suggest a simple thing - let's continue here "until everything ready", then you reorganize repo for your comfortable maintainability in general as you wish. I'm not against moving to lvgl (that's your project, you decide), but it looks a bit early now.

What benefits of keeping things here:

- Physical guarantee of good isolation and no tight-coupled code :).
- Possibility to create tests, without pressure of big project approaches.
- Light sandbox for me, to experiment with CI scripts

> `init` and `set_local` really can have return codes. but logs are also useful to see what happens in `get_text` and `get_text_plural`.

This practice tend to forget about testability, because "we have one big magical log, where everything can be seen". I say so, because did the same things :). As soon, as you try to write unit tests, you will see tons of missed return codes. 

I'm not against logs, i'm for _guarantees_ of code correctness. This is achieved by unit tests & good coverage. I did so for JS, and would like to achieve the same for C.

----

Question about code, https://github.com/littlevgl/lv_i18n/blob/examples/examples/manual/trans.c#L41-L43

Could not find definition of `LV_I18N_PLURAL_TYPE_ZERO`, `LV_I18N_PLURAL_TYPE_ONE` & `LV_I18N_PLURAL_TYPE_MANY`. Do i miss something?

**Comment by puzrin** [comment]
General notes about data structures https://github.com/littlevgl/lv_i18n/blob/examples/examples/manual/trans.c

- Idea to place text keys in every list is really nice (i expected autogenerated enums, but your solution is better)
  - Quick estimate: plurals take 10-15% (worst) of keys count. Translation is unicode, 2 bytes at least (twice bigger than original in english). At first glance, total waste < 10-20%, compared to more optimized forms. Looks good.
- `{ NULL, NULL }` - looks a bit suspicious, seems ready for raw scans only, not for binary search. May be worth to make data ready for binary search? If someone wish to improve C code, it will not be needed to redesign structures again and update JS generator.

**Comment by puzrin** [comment]
https://github.com/littlevgl/lv_i18n/commit/3577bfd33b531aa128c13d807ce4e4178b2b07fe

Temporary commit, attempt to recombine your sources to "something with test", header-only.

```
cd test/c
make test-deps
make test
```

Could you explain how to fix compile errors?

**Comment by kisvegabor** [comment]
> This practice tend to forget about testability, because "we have one big magical log, where everything can be seen". I say so, because did the same things :). As soon, as you try to write unit tests, you will see tons of missed return codes.

I'll add return values there :)

> Quick estimate: plurals take 10-15% (worst) of keys count. Translation is unicode, 2 bytes at least (twice bigger than original in english). At first glance, total waste < 10-20%, compared to more optimized forms. Looks good.

I agree. The `msg_id`s are stored in the flash anyway (when the user types them in his code) here the waste is the 4 byte pointer to them. In memory usage, it looks like all plurals are 4 byte longer. It is quite a little cost for having a more robust and clean structure.

> `{ NULL, NULL }` - looks a bit suspicious, seems ready for raw scans only, not for binary search. May be worth to make data ready for binary search? If someone wish to improve C code, it will not be needed to redesign structures again and update JS generator.

The disadvantage of the binary search is the length of the list need to be known. But if the length is `0` the list can be treated as an unordered.

> Could you explain how to fix compile errors?

I've fixed the build errors. It was mainly some missing `const`s.
But there was an issue with `printf` too because it wants `char *` if `%s` is specified but `lv_i18n_get_text` return `void *`. `void *` has the advantage that we can return with anything (not only texts) for example, an image which is different in different locals. I think this "incompatibility" with printf is not important.

**Comment by puzrin** [comment]
> I've fixed the build errors. It was mainly some missing `const`s.

Thanks. I'll try to write unity tests.

> The disadvantage of the binary search is the length of the list need to be known. But if the length is `0` the list can be treated as an unordered.

I don't understand. Is it a problem to know length?

- It can be generated by JS. When file is saved, we know exact number of elements.
- If you don't like to hardcode length, it can be calculated (via scan) in `lv_i18n_init()`. In this case we need additional non-const struct to store this data.

Of cause, this will make file less "editable by hand". But... who cares... :) ? We discussed this earlier - it's impossible to keep file both effective and "human-writeable" at once (but still possible to keep "human-readable").

> But there was an issue with `printf` too because it wants `char *` if `%s` is specified but `lv_i18n_get_text` return `void *`. `void *` has the advantage that we can return with anything (not only texts) for example, an image which is different in different locals. I think this "incompatibility" with printf is not important.

Hm... i'd say forced cast will be required everywhere, when user try to use `_()` as param. That can trash shorteness/beauty of `_()` wrapper. And nobody prohibit keep image as base64 string or recast (char *) type via union and so on. Also, we can add something like `const void * lv_i18n_get_void()`, without shortcuts, for special cases.

Let's try to check some stats:

- What original gettext says about this? Does is provides functions with void result?
- Which pattern [probability] is more often in user code?
  - use `_()` as function param, with required `const char *`
  - use `_()` to localize other types of data.

My C experience is not enoigth to give relevant answer. The only samples i have - writing tests for this code, with tons of `_()` params in asserts (compare strings).

**Comment by puzrin** [comment]
Need comment about this data set in your example:

```c
lv_i18n_trans_t en_gb_zero[] = {
    {"dog", "I have no dogs yet."},
    {"cat", "My friend has no cats yet."},
    {NULL, NULL},       /*Mark that there is no more translations*/
};

lv_i18n_trans_t en_gb_one[] = {
    {"dog", "I have only one dog."},
    {"cat", "My friend has only one cat."},
    {NULL, NULL},       /*Mark that there is no more translations*/
};

lv_i18n_trans_t en_gb_many[] = {
    {"dog", "I already have %d dogs."},
    {"cat", "My friend already has %d cats."},
    {NULL, NULL},       /*Mark that there is no more translations*/
};
```

`en-GB` locale has only 2 forms, `one` and `other`. Rename `many` -> `other` is clear. But what about zero form? What is recommended way to support it in gettext? Shouldn't it be a standalone phrase, with key `no_dog`?

**Comment by puzrin** [comment]
https://github.com/littlevgl/lv_i18n/commit/2a9d78dc4d11e88ae1355730b0868e4b4db78952 - added tests and fixed assorted issues. 

Tests for singulars & plurals should be extended, but i'd like to clarify previous questions prior to continue.

**Comment by puzrin** [comment]
https://github.com/littlevgl/lv_i18n/blob/2a9d78dc4d11e88ae1355730b0868e4b4db78952/src/lv_i18n.template.h

More comments about data structure:

1. Worth to prefix all vars, and add __ to "private" ones.
2. May be worth to "inline" all small structs into parents, instead of declare as separate variables? Don't know it this needed or not.

**Comment by puzrin** [comment]
Commited coverage report. `Makefile` is very dirty, but should work somehow.

```sh
make test-deps
make test-coverage
```

Then open `test/c/coverage/coverage.html`, enjoy :)

**Comment by puzrin** [comment]
@embeddedt may be you have time to join for review of https://github.com/littlevgl/lv_i18n/blob/vit_c_sample/src/lv_i18n.template.h?

This is suggested to be single file for `#include` into user sources (with custom injected phrases). Do you like this?

**Comment by embeddedt** [comment]
@puzrin Putting global function bodies into a header file is bad practice and should be avoided. It makes it impossible to include the header in more than one source file. That code could go into a file called `lv_i18n.template.c`.

**Comment by puzrin** [comment]
Hm... is that C limitation? I'm interested to simplify integration process as much as possible:

- user have to generate at least 1 file with translations, this can be avoided.
- if user should not include extra libraries - that's good
- if user should inlude 1 file instead of 2 files - that ideal.

What can be acheived in our case and how? I will accept any recommended final template.

**Comment by kisvegabor** [comment]
> I don't understand. Is it a problem to know length?
> * It can be generated by JS. When file is saved, we know exact number of elements.
> * If you don't like to hardcode length, it can be calculated (via scan) in `lv_i18n_init()`. In this case we need additional non-const struct to store this data.

If you only have a pointer to an array in C you can't get its size. (E.g. There is no `array.length()` or similar)

> Hm... i'd say forced cast will be required everywhere, when user try to use `_()` as param. ...

In LittlevGL a pointer to a `struct` can represent an image ([example](https://github.com/littlevgl/lv_examples/blob/master/lv_tests/lv_test_objx/lv_test_img/img_flower_icon.c#L181)). It can be the return value of `_` because the images can be localized too. However, it will happen very rarely and need to be done manually anyway. If done manually the cast can be added in `trans.c` too. In this case the scripts should **support non-string translations** (like `"dog", &dog_image_english`). Is it ok?

> `en-GB` locale has only 2 forms, `one` and `other`. Rename `many` -> `other` is clear. But what about zero form? What is recommended way to support it in gettext? Shouldn't it be a standalone phrase, with key `no_dog`?

I think it's not expected by the standard `gettext` but practical IMO. Zero can have special "writing" in other languages too. The solution can be to add `zero` every language. If it's the same as `one` the string will be used so it has no notable memory impact.

> 1. Worth to prefix all vars, and add __ to "private" ones.

I made them private with `static` keyword.


> 2. May be worth to "inline" all small structs into parents, instead of declare as separate variables? Don't know it this needed or not.

The current implementation is more readable I think.

> Putting global function bodies into a header file is bad practice and should be avoided. It makes it impossible to include the header in more than one source file. That code could go into a file called `lv_i18n.template.c`.

I agree. I touhgt you are using the header file because of something special.

**Comment by puzrin** [comment]
> In this case the scripts should **support non-string translations** (like `"dog", &dog_image_english`). Is it ok?

The most difficult thing in API design is say to self "i should stop" before everything become messed :). My default approach is to be very conservative, and not add anything if this can be not added.

- check, if request can be implemented with existing features (store image as base64, for example)
- check if feature can be postponed (may be implement via lv_i18n_get_void() later, if really required)

Another important point - incomplete implementations are evil. They make API messy, require care for maintainance but may be never implemented in real world. Current "images" feature is NOT supported in yaml format and generator. We have no use-case description how user will manage such content.

Conclusion:

- I'd vote to "postpone" in favour of something like base64/get_void (and hope this will never be required :smile:)

> I think it's not expected by the standard `gettext` but practical IMO. Zero can have special "writing" in other languages too. The solution can be to add `zero` every language. If it's the same as `one` the string will be used so it has no notable memory impact.

This may look attractive, by tend to diverge from standard. For example, if you export translations to web, it may be not clear why you should add unexpected plural forms.

Now this can be solved in standard way:

```c
const char* txt = num ? _("i have %n dogs") : _("i have no dogs");
```

Having embedded zero form may look a bit more simple, but added value is not so big to diverge from standard.

- I vote to reject this extension, because side effects are bigger than added value.

> I agree. I touhgt you are using the header file because of something special.

That's because i actively used C 20 years ago, and now type it with one finger :). All my related questions about variables hide are not relevant then. I will fix sources soon and let you know.

**Comment by puzrin** [comment]
@kisvegabor Review please

https://github.com/littlevgl/lv_i18n/commits/vit_c_sample

2 commits:

- Separated files back to `.h` & `.c`
- Tried to make names more descriptive

I don't like this export:

https://github.com/littlevgl/lv_i18n/blob/vit_c_sample/src/lv_i18n.h#L33

```c
extern const lv_i18n_lang_t ** languages
```

Can we expose it as pointer to `lv_i18_lang_pack_t`? User should not know details about "language", it inits lib with "language pack". Don't know how to write it in C right.

## Current use concept

- User works with `lv_i18n` and finally get 2 files (`.c` & `.h`) to his dir
- No external dependencies, code is self sufficient. User need only to install `lv_i18n` with `npm`.

**Comment by puzrin** [comment]
@kisvegabor i'd like cleanup all experimental garbage and move forward.

Could you commit [this 2 files](https://github.com/littlevgl/lv_i18n/tree/vit_c_sample/src) into `dev` branch as "Added C templates", to reflect your authorship, and i will go forward with other things.

**Comment by kisvegabor** [comment]
> I'd vote to "postpone" in favour of something like base64/get_void (and hope this will never be required

Ok, let"s postpone it and we will see :)

> Having embedded zero form may look a bit more simple, but added value is not so big to diverge from standard.

Although it's not standard it seems very reasonable. What about adding an option to the scripts to always generate `zero`?

> Can we expose it as pointer to `lv_i18_lang_pack_t`? User should not know details about "language", it inits lib with "language pack". Don't know how to write it in C right.

Added [here](https://github.com/littlevgl/lvgl/blob/i18n/lv_core/lv_i18n.c#L47). I also added simple integer return values as you did in the template. The [example](https://github.com/littlevgl/lv_i18n/blob/examples/examples/manual/trans.c#L57) is also updated.

> Could you commit [this 2 files](https://github.com/littlevgl/lv_i18n/tree/vit_c_sample/src) into `dev` branch as "Added C templates", to reflect your authorship, and i will go forward with other things.

Do you mean to `lvgl` repo?

**Comment by puzrin** [comment]
> Although it's not standard it seems very reasonable. What about adding an option to the scripts to always generate `zero`?

Technically, we can. But why should we diverge from standard when native implementation not much worse?

```c
const char* txt = num ? _p("i have %n dogs", num) : _("i have no dogs");
// instead of
const char* txt = _p("i have %n dogs", num);
```

and zero-alternative in almost the same place of yaml file.

When you follow standard, you have guaranty of transparency with 3rd-party tools (web translators, for example).

As developper of js-yaml, i've seen many time when people tried to use it's notation as programming language. This looks very attractive at first glance, but very bad idea in general. You suggest to follow similar way with i18n. I'm agains't doing this. But as compromiss, i suggest to postpone for several months, and try more standard solutions first.

> Do you mean to `lvgl` repo?

No. Here https://github.com/littlevgl/lv_i18n/tree/dev.

Current active branch has many temporary commits to show intermediate things, check different approaches and so on. I don't like to expose all this garbage to final result.

If everything were done by me, i could just squash all into single commit myself. But in fact, C files were mostly yours, in i think it will be correct if you recommit manually latest result yourself into dev branch. Then i can continue with the rest.

**Comment by puzrin** [comment]
Ping. Please recommit 2 files from `./src` to `dev` branch, as requested here https://github.com/littlevgl/lv_i18n/issues/7#issuecomment-466686801. This blocks me from landing other parts.

**Comment by kisvegabor** [comment]
> As developper of js-yaml, i've seen many time when people tried to use it's notation as programming language. This looks very attractive at first glance, but very bad idea in general. You suggest to follow similar way with i18n. I'm agains't doing this. But as compromiss, i suggest to postpone for several months, and try more standard solutions first.

Ok

> Ping. Please recommit 2 files from `./src` to `dev` branch, as requested here [#7 (comment)](https://github.com/littlevgl/lv_i18n/issues/7#issuecomment-466686801). This blocks me from landing other parts.

Done

**Comment by puzrin** [comment]
Thanks!

Do i understand right, that type of `lv_i18_get_text()` can be changed from `const void *` to `const char *`?

**Comment by kisvegabor** [comment]
> Do i understand right, that type of `lv_i18_get_text()` can be changed from `const void *` to `const char *`?

Yes, I updated it in `lvgl`. The `i18n` branch is merged to `dev-6.0`.
See: https://github.com/littlevgl/lvgl/blob/dev-6.0/lv_core/lv_i18n.c#L100

**Comment by puzrin** [comment]
https://github.com/littlevgl/lv_i18n/tree/dev updated branches with latest "stable" things.

- Only "compiler" missed (started to implement)
- C api added to CI tests https://travis-ci.org/littlevgl/lv_i18n

I think it worth to discuss other pending things. Those do not block compiler write, but should be solved anyway.

- Is examples branch needed? 
  - (?) you may be planned additional folders with sample code, but IMO readme is now enougth.
- Does lvgl really needs "embedded" i18n? I see no benefits.
- Current implementation in `lvgl` repo diverges from this one. This one expects compiler to generate 2 files (first time mentioned this in https://github.com/littlevgl/lv_i18n/issues/7#issuecomment-466484600)
  - i've updated readme to reflect current state

Let me know what do you think

**Comment by puzrin** [comment]
https://github.com/littlevgl/lv_i18n/commits/compiler

Compiler branch contains useable code. I did not finished yet, but have some questions. See attached coverage report (pay attention to missed branches too, red "X" in left column).

[coverage.zip](https://github.com/littlevgl/lv_i18n/files/2908278/coverage.zip)

1. Some conditions seems unreacheable (`lang->plurals == NULL`)
2. https://github.com/littlevgl/lv_i18n/blob/5c8d15abea94e13bcfdbf04da9de0ecd04ad1418/test/c/test.c#L180 i could not understand why, but one test crashes (had to disable those lines)

In general, C code is ready for review. It would be nice to stabilize API.

Current plans are:

- Add missed JS tests
- Improve C branches coverage (see questions above)
- Generated plural functions are left untested
  - too boring to port everything from JS
  - i copy-pasted well-tested code, hope everything will be fine (en/ru/de fn-s seems correct)

**Comment by puzrin** [comment]
https://github.com/littlevgl/lv_i18n/tree/dev

I've added the rest of JS tests & squashed final result into dev & master branches. No more things left from my side.

Everything else related to C API and internals (coverage-related questions and bugs).

**Comment by kisvegabor** [comment]
Nice progress!

> * Is examples branch needed?

We can delete it.

> * Does lvgl really needs "embedded" i18n? I see no benefits.

You said this earlier:
> Well, i suggest a simple thing - let's continue here "until everything ready", then you reorganize repo for your comfortable maintainability in general, as you wish. I'm not against moving to lvgl (that's your project, you decide), but it looks a bit early now.

So there are two reaonable ways:
1. Move the scripts and leave `lv_i18n.c/h` in `lvgl`. Easy for the user, use one repo
2. Leave the scripts here and move `lv_i18n.c/h` here. It results in a standalon tool.

I'm not sure which one is better. 

> 1. Some conditions seems unreacheable (`lang->plurals == NULL`)

Why are those inreachable? With broken translation it should be reacher. Or have I messed something?

**Comment by puzrin** [comment]
> I'm not sure which one is better.

- I see no benefits of having scripts & templates in lvgl (may be lvgl has requirements to depend on lv_i18n header, but i don't know such details). User will have to install tools via npm anyway. Nobody do it via repo clone.
- Benefits of having it separate - much better maintainability, right now (see tests, ci, coverage reports).

May be... it could be convenient to have mono-repository (with subprojects in root subfolders), but since it's not available, i'm for strong isolation, if project is really independent.

Right now compiler generates 2 files into user dir (.c/.h). No extra dependencies - just install tool via npm. As user, i can not imagine more "simple" thing for C.

>> Some conditions seems unreacheable (`lang->plurals == NULL`)
>
> Why are those inreachable? With broken translation it should be reacher. Or have I messed something?

https://github.com/littlevgl/lv_i18n/blob/73ad233cb0580e083ed05be1e0d21d3cfd67cddd/src/lv_i18n.h#L29

As far as i understand this declaration, `lang->plurals` can be fixed array of NULL, but can not be NULL itself (may be i confused C features with something else again, sorry). Array can not be null even if translation is broken on logical level (still generated by C compiler, not by random blob generator)

I this case condition `lang->plurals == NULL` will never be satisfied.

**Comment by kisvegabor** [comment]
Ok, let's try the isolation and we will how it works. But then here an untouched version of  `lv_i18n.c/h` should be used to keep the core code clear and easy to update. And translation can be in `translations.c/h`.

>  As far as i understand this declaration, `lang->plurals` can be fixed array of NULL, but can not be NULL itself (may be i confused C features with something else again, sorry). Array can not be null even if translation is broken on logical level (still generated by C compiler, not by random blob generator)

You are right. I updated it.

**Comment by puzrin** [comment]
> Ok, let's try the isolation and we will how it works. But then here an untouched version of `lv_i18n.c/h` should be used to keep the core code clear and easy to update. And translation can be in `translations.c/h`.

Probably, i don't understand something. What do you mean as "core code"? Do you still wish to manually copy this code into lvgl? That will trash all effect of isolation.

If you mean core code of this repo - why should we keep clean version if existing one is already ok?

- https://github.com/littlevgl/lv_i18n/tree/master/support data can be updated with ease
- Sources are covered with tests. You can change those anytime as needed.

I followed principle "result should be conveniend for user first". 2 output files looks more clear than 3. Did i missed something?

**Comment by puzrin** [comment]
https://github.com/littlevgl/lv_i18n/commit/26c8a17d69662b8d6fc00cae1f43d296650d076f

Before this change logic of `get_text` & `get_text_plural` was too spread between different branches. I did it more straight and focused. This also removed 1 bug, mentioned before (caused test crash). Also added tests for 100% coverage (except demo data). Now i'm satisfied with result, and we have to solve only organizational questions:

- You mentioned about different C code structure (see my reply)
- I used `__attribute__((undef))` to avoid warnings - is it compatible with your C requirements?
- It worth to review C code, readme & play with scripts.
- Any other notes to fix?

**Comment by embeddedt** [comment]
Don't use `__attribute__((unused)`. Instead, cast the unused parameters to void inside the function, like so:

```c
static uint32_t op_v(uint32_t val)
{
    (void)val;
    return 0;
}
```

**Comment by puzrin** [comment]
@embeddedt thank you! I will try. How about unused functions? See https://github.com/littlevgl/lv_i18n/blob/9ea1158212c2520c994f08ba6306f6625c284f50/src/lv_i18n.template.c#L21-L37

Those are partially used, depending on generated plural functions. It would be very inconvenient to write dynamic head generator.

One more question. What is minimal supported C version and is it possible to force it in makefile options? I'd like to automate compatibility checks.

**Comment by embeddedt** [comment]
@puzrin We can add an `LV_ATTRIBUTE_UNUSED` attribute to `lv_conf.h` that you can use instead of `__attribute__((unused))`.

The minimum C version is C99.

**Comment by puzrin** [comment]
This package is isolated from lvgl, it should not use `lv_conf.h`

- Why use of `__attribute__((unused))` is bad? (i don't know C details well)
- is `static inline` good for such goal here (tested, seems to work)?

> The minimum C version is C99 (use `-std=c99`).

Thanks, i will try.

**Comment by puzrin** [comment]
https://github.com/littlevgl/lv_i18n/blob/9ea1158212c2520c994f08ba6306f6625c284f50/test/c/Makefile#L10

Hmm... `-std=c99` already exists. That returns us to question "why `__attribute__((unused))` is considered as bad pratice". I don't resist, just like to understand.

**Comment by puzrin** [comment]
https://github.com/littlevgl/lv_i18n/commit/dd7f11741b830d35fb6ccae47a316d30183805c7

Seems to removed `__attribute__((unused))`. If that's correct, i will merge to main branches.

**Comment by embeddedt** [comment]
`__attribute__((unused))` is too compiler-specific. If we're going to use it it needs to be set up in such a way that it will only apply to compilers that support it. It's better to avoid the use of attributes whenever possible.

**Comment by kisvegabor** [comment]
> Probably, i don't understand something. What do you mean as "core code"? Do you still wish to manually copy this code into lvgl? That will trash all effect of isolation.

I ment to have 4 files:
1. lv_i18n.c 
2. lv_i18n.h 
3. translation.c 
4. translation.h

To isolate the logic from the translations. Mixing them looks messy.

**Comment by puzrin** [comment]
> To isolate the logic from the translations. Mixing them looks messy.

Do you agree that user don't cares about internals and will prefer minimal number of files (2 now)?

May be later, if we add index data, binary search and so on, file become big and will be more convenient to split. But now it doesn't look necessary - only 300 lines, i worked with it, and it was convenient enougth.

**Comment by kisvegabor** [comment]
I think it's import to make easy to update/fix things in the logic. It also makes the code more readable. 

So I see no reason to generate these files content too.

**Comment by puzrin** [comment]
Probably, we have different look how this library will be used. Could i explain your one?

Me, as user:

- install npm package
- create yaml files
- edit yaml files
- generate/update 2 files  (c/h)
- feel happy

Here are no step "look into generated source and investigate content"

**Comment by kisvegabor** [comment]
I see your point about simplicity for the user. I complain about the ease of development.  How to add a new feature if the "i18n logic" is generated? 

What I can image is to have a `i18n_logic.c/h` whose content is copied to the the final translation file. This would allow to easily update the logic later but still result's in one c/h file.

**Comment by puzrin** [comment]
> I complain about the ease of development. How to add a new feature if the "i18n logic" is generated?

1. First,i'd suggest to wait until someone wish to change C source :). If this happens after 5 years, why should we care now? 

2. `i18n logic` is not generated. Only translation data is replaced between [2 comment lines](https://github.com/littlevgl/lv_i18n/blob/dd7f11741b830d35fb6ccae47a316d30183805c7/src/lv_i18n.template.c#L3-L154). Script in `support/` folder is to quickly update test data. But you are not forsed to update it. Keep it old, edit manually - do anything you wish.

I could understand splitting files > 500-1000 lines. But 300 lines only are ok imho. Form my point of view it's also convenient to test resulting file exactly as user see.

And, as a side note... i participated in development a bit, and did not noticed inconvenience :)

**Comment by kisvegabor** [comment]
> 2. `i18n logic` is not generated. Only translation data is replaced between [2 comment lines](https://github.com/littlevgl/lv_i18n/blob/dd7f11741b830d35fb6ccae47a316d30183805c7/src/lv_i18n.template.c#L3-L154). Script in `support/` folder is to quickly update test data. But you are not forsed to update it. Keep it old, edit manually - do anything you wish.

I see, it's fine this way. Thank you for the explanation!

Just one note: let's change
`const char * __lv_i18n_get_text_core(lv_i18n_phrase_t * trans, const char * msg_id)`  
to  
`static const char * lv_i18n_get_text_core(lv_i18n_phrase_t * trans, const char * msg_id)`

This way it won't be available out of this file. Now ` __lv_i18n_get_text_core` is still visible.

**Comment by puzrin** [comment]
Fixed. Seems no more questions?

**Comment by kisvegabor** [comment]
Just one more thing: The `op_...` functions are really required? They are for very simple things. Or are they related to tests?

**Comment by puzrin** [comment]
"Operands" required to express plural rules in the same way as in original. 

- [original](https://github.com/unclenachoduh/pluralrules/blob/74686f95dacf0e01092f6ebdac016525f3182915/intl_pluralrules/cldr_data/cldr_pluralrules_cardinals.json#L616) CLDR expressions for RU
- [generated](https://github.com/littlevgl/lv_i18n/blob/28c3574b935446fed700d46d75d0a9624c753240/src/lv_i18n.template.c#L75) code.

Operands meaning: http://unicode.org/reports/tr35/tr35-numbers.html#Operands.

Current op_ implementation looks dummy because lack of float support.

**Comment by kisvegabor** [comment]
Clear, thank you.

No more questions :)
