### ISSUE TITLE
package/repo name

### ISSUE THREAD

**Issue by puzrin** [littlevgl/lv_i18n#8]
i18n is too generic to publish in global catalogs (platformio for example)

Possible alternatives:

- `lvgl_i18n`
- `lvgl_t`
- suggestions?

**Comment by kisvegabor** [comment]
We can emphasize that it's a lightweight form of gettext or i18n. 
- `i18n_light` 
- `gettext_light`
- `e8d_i18n`for embedded internationalization

**Comment by puzrin** [comment]
`shitty_gettext` :)

**Comment by kisvegabor** [comment]
Not bad but rather `tiny_gettext`?

**Comment by puzrin** [comment]
IMHO it's confusing to mention gettext and any for of "smaller".

Still prefer `lvgl_i18n`

**Comment by embeddedt** [comment]
`lvgl_i18n` sounds reasonable to me.

**Comment by puzrin** [comment]
Hm... at this page https://github.com/littlevgl only `lv_` prefix is used in repo names.

May be `lv_i18n` then?

**Comment by puzrin** [comment]
https://github.com/littlevgl/i18n/issues/4#issuecomment-462073252

From the other hand... For ulility name i like `lv-t`. Then it would be logical  use `lv_t` for repo and published packages.

**Comment by embeddedt** [comment]
@puzrin `lv_t` isn't really that descriptive of a name. While our other repository names are also quite short, they give you a reasonable description of what to expect inside.

**Comment by puzrin** [comment]
And you are right too :). What do you think about utility name and functions? `lv-i18n` for executable script seems strange. I can't explain why.

**Comment by kisvegabor** [comment]
In LittlevGL `lv_lang_...` function would be better because `lang` is quite self-explaining. `i18n` is not clear for everybody. I also needed to check what it means when we started to discuss about it.

For the script name, maybe one word would be better. `ei18n`: Embedded i18n?

The repo name can have `lv_` prefix but it's not mandatory because it can work with other projects too (not only for lvgl).

**Comment by puzrin** [comment]
> In LittlevGL `lv_lang_...` function would be better because `lang` is quite self-explaining. `i18n` is not clear for everybody. I also needed to check what it means when we started to discuss about it.

"i18n" is de-facto standard term and the main search keyword. Avoiding well known terms looks strange. Of cause, when people see awesome lib, the will not think it can be created by idiots. But they may thinks authors have very strange humour :).

I understand, i18n may be unusual for you right now. But IMO after several months you will say the same about "lang" :)

**Comment by kisvegabor** [comment]
I need to mention that not only programmers with many years of experience use LittlevGL. For them, a common phrase like `lang` would be easier to understand and remember.  

But for veterans `i18n` really might be better.

So I have no good arguments because one group would like this the other would like that. So finally I'm ok with `lv_i18n_...` because it's the already existing terminology. @embeddedt, do you agree?

**Comment by embeddedt** [comment]
@kisvegabor We could use `i18n`, then put what that means in the description of the repository. That would still make it understandable to those who don't know the official term.

**Comment by puzrin** [comment]
I see no problem to add link in readme or use full word "internationalization" in description. Let's promote good things. This experience will be reusable in other projects.

PS. You may be interested to know abbreviation "l10n" - localization. That means, how to use language-specific numbers formattings, dates formatting and so on. All info described in Unicode CLDR.

**Comment by embeddedt** [comment]
@puzrin Now that you mention the second abbreviation I just realized how the abbreviation works. It refers to the number of letters between the first and last letter. Interesting!

* `i18n` - `i<18 letters>n`
* `l10n` - `l<10 letters>n`

**Comment by puzrin** [comment]
Yes :). That's from ancient ages. Nobody use this now to create new terms, but old one became "standard", and "can not be changed".

**Comment by puzrin** [comment]
@kisvegabor 

If no principal objections, please do this actions:

1. Rename this repo to `lv_i18n`
2. Enable Travis-CI (login to https://travis-ci.org/, settings -> grganization -> turn on switch for this project). If can't find project, or it's name not updated - press `sync` button first.

**Comment by kisvegabor** [comment]
Both are done!

**Comment by puzrin** [comment]
Thanks!

Close as solved.

**Comment by puzrin** [comment]
I've started to move forward, and suggest to consider this repo as sanbox for "all that modern tricks":

- how to attach CI
- how to create unit tests & check code coverage
- how to create nice "local" demo and simplify publishing of web build on gh-pages.

If you like something - you can spread this to other repos. Here i have enougth permissions to check everythig and not crash valuable things :).

Also, note, i'd like to use here "github flow" process, at least, at first stage. That means: "temporary, please, don't push to `master` and `dev` branches, until i finish fill repo with some meat".

- all new features/experiments goes in separate branches, and merged to `dev` when ready.
- as soon as package become useable, dev will be merged to `master` and not used anymore.

**Comment by kisvegabor** [comment]
> I've started to move forward, and suggest to consider this repo as sanbox for "all that modern tricks":
> If you like something - you can spread this to other repos. Here i have enougth permissions to check everythig and not crash valuable things :).

Curiously waiting to see these things in action.

> Also, note, i'd like to use here "github flow" process, at least, at first stage. That means: "temporary, please, don't push to `master` and `dev` branches, until i finish fill repo with some meat".

Clear!
